export const reducerCases = {
    SET_TOKEN : "SET_TOKEN",
    SET_PLAYLISTS : "SET_PLAYLISTS",
    SET_USERINFO : "SET_USERINFO",
    SET_PLAYLIST : "SET_PLAYLIST",
    SET_PLAYING : "SET_PLAYING",
    SET_PLAYER_STATE: "SET_PLAYER_STATE",
    SET_SELECTED_PLAYLIST_ID : "SET_SELECTED_PLAYLIST_ID",
    SET_SEARCH_CLICK: "SET_SEARCH_CLICK",
    SET_HEADER_BG: "SET_HEADER_BG",
    SET_NAV_BG: "SET_NAV_BG",
    SET_VOLUME_STATE : "SET_VOLUME_STATE",

}